version: '3'

services:
  db:
    image: mysql:8.0.34
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
      - MYSQL_DATABASE=flask
      - MYSQL_TCP_PORT=3306
    ports:
      - "3306:3306"

  flask:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db
      - DB_PORT=3306
    command:
      - '--local-infile=1'
    depends_on:
      - db